//%attributes = {"invisible":true}
var bCancel : Real
var bDelete : Real
var bFirst : Real
var bLast : Real
var bNext : Real
var bPrevious : Real
var bValidate : Real
var Header1 : Real
var Header2 : Real
var Header3 : Real
var OutputVar : Text
var Splitter10 : Real
var Splitter11 : Real
var Splitter12 : Real
var Splitter13 : Real
var Splitter2 : Real
var Splitter3 : Real
var Splitter4 : Real
var Splitter5 : Real
var Splitter6 : Real
var Splitter7 : Real
var Splitter8 : Real
var Splitter9 : Real
var vRecNum : Text
